version: '3.9'

services:
  user-service:
    build:
      context: ../ERPSystem/UserService
    ports:
      - "5000:80"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - kafka

  inventory-service:
    build:
      context: ../ERPSystem/InventoryService
    ports:
      - "5001:80"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - kafka

  order-service:
    build:
      context: ../ERPSystem/OrderService
    ports:
      - "5002:80"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - kafka

  frontend:
    build:
      context: ../erp-frontend
    ports:
      - "3000:3000"
    depends_on:
      - user-service
      - inventory-service
      - order-service

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
