# version: '3.9'

services:
  user-service:
    build:
      context: ../ERPSystem/UserService
    ports:
      - "5000:80"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - kafka

  inventory-service:
    build:
      context: ../ERPSystem/InventoryService
    ports:
      - "5001:8080"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - kafka

  order-service:
    build:
      context: ../ERPSystem/OrderService
    ports:
      - "5002:8080"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - kafka

  frontend:
    build:
      context: ../erp-frontend
    ports:
      - "3000:3000"
    depends_on:
      - user-service
      - inventory-service
      - order-service

  kafka:
    image: bitnami/kafka:3.6
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_password123
    ports:
      - "1433:1433"
